---
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - name: ruff
        id: ruff
        entry: poetry run ruff --fix ./
        language: system
        types_or: [cython, pyi, python]

      - name: isort
        id: isort
        entry: poetry run isort ./
        language: system
        types_or: [cython, pyi, python]

      - name: black
        id: black
        entry: poetry run black ./
        language: system
        types_or: [cython, pyi, python]

      - name: pyright
        id: pyright
        entry: poetry run pyright ./
        language: system
        types_or: [cython, pyi, python]
