---
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - name: ruff-format
        id: ruff-format
        entry: poetry run ruff format ./
        language: system
        types_or: [cython, pyi, python]

      - name: ruff-lint
        id: ruff-lint
        entry: poetry run ruff ./
        language: system
        types_or: [cython, pyi, python]

      - name: pyright
        id: pyright
        entry: poetry run pyright ./
        language: system
        types_or: [cython, pyi, python]
