[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = "\"Programming puzzles completed with Python 3.10 for advent of code 2021\""
authors = ["Jason Kai <tkai@uwo.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
pytest = "^6.2.5"
pytest-mock = "^3.6.1"
pylint = "^2.11.1"
isort = "^5.10.1"
flake8 = "^4.0.1"
poethepoet = "^0.10.0"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
setup = "pre-commit install"
quality = { shell = "isort snakebids && black snakebids && flake8 snakebids && pylint snakebids" }
test = "pytest"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
ignore-patterns = "^[0-9][0-9]+_,^test_"

[tool.pylint.format]
good-names = "i,j,k,ex,_,x,y,f,d"

[tool.pylint.messages_control]
disable = """
    missing-function-docstring,
    missing-module-docstring,
    fixme
"""
