---
# Bump date version to indicate completion

name: Increment date
on:
  pull_request_target:
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Get current date
        run: DATE=$(echo $(date +'%Y.%m.%d')) >> $GITHUB_ENV

      - name: Update date in pyproject.toml
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: pyproject.toml
          find: version = "([0-9]+\.[0-9]+\.[0-9]+)"
          replace: version = "${{ env.DATE }}"

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff-index --quiet HEAD || git commit -m "Bump date to ${{ env.DATE }}" -a

      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          branch: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.PAT }}
          unprotect_reviews: true
